log:
  single-line: false
  skip-classes: >
    FastClassBySpringCGLIB,
    EnhancerBySpringCGLIB,
    java.lang.reflect.Method.invoke,
    jdk.internal.reflect,
    org.apache.catalina,
    org.apache.coyote,
    org.apache.tomcat,
    org.springframework.aop.framework,
    org.springframework.aop.aspectj,
    org.springframework.cglib.proxy.MethodProxy.invoke,
    org.springframework.security.web.FilterChainProxy,
    org.springframework.web.filter.OncePerRequestFilter.doFilter,
    org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke,
    org.springframework.web.method.support.InvocableHandlerMethod,
    org.springframework.web.servlet.mvc.method.annotation,
    org.springframework.web.filter,
    it.vitalegi.budget.metrics.PerformanceAspect.logExecutionTime

metrics:
  skipIfLessThan: 50

mangars:
  - type: COMIKO
    name: Mahou Sensei Negima
    enabled: true
    uri: https://comiko.net/series/38589
    outDir: ./negima
    volumes:
      leftPadding:
        length: 2
        character: '0'
      overrideIds:
        - type: IS_NULL
          value: 36
    chapters:
      leftPadding:
        length: 3
        character: '0'
      overrideIds:
        - type: IS_NULL
          value: 999
        - type: EQUALS
          param: 344v2
          value: 344
    pages:
      leftPadding:
        length: 3
        character: '0'
      overrideIds: